In [2]:
import numpy as np

## Funções aritimetricas : soma Subitração e divisão

In [2]:
#Criação de dois arrays x e y
x =  np.ones((2,2))
y =  np.eye(2)
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [3]:
#Soma
print("Soma de dois arrays:\n ", x + y)
print("Soma com float/int:\n ", x + 2) #broadcast

Soma de dois arrays:
  [[2. 1.]
 [1. 2.]]
Soma com float/int:
  [[3. 3.]
 [3. 3.]]


In [4]:
#Subtração
print("Subtração de dois arrays:\n ", x - y)
print("Subtração com float/int:\n ", x + 2) #broadcast

Subtração de dois arrays:
  [[0. 1.]
 [1. 0.]]
Subtração com float/int:
  [[3. 3.]
 [3. 3.]]


In [5]:
#Divisão
print("Divisão de dois arrays:\n ", x / y)
print("Divisão com float/int:\n ", x / 2) #broadcast

Divisão de dois arrays:
  [[ 1. inf]
 [inf  1.]]
Divisão com float/int:
  [[0.5 0.5]
 [0.5 0.5]]


C:\Users\JG Silva\AppData\Local\Temp\ipykernel_9916\2777928150.py:2: RuntimeWarning: divide by zero encountered in divide
  print("Divisão de dois arrays:\n ", x / y)


In [6]:
#Qaundo o broadcast não funciona
np.array([1,2,3]) + np.array([1,2]) 

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
#Soma subtração e divisão
print("Combinação d eoperações:\n ",(x+y) /(x - 2))

# agora com a mutiplicação Caso particular 

In [ ]:
#Multiplicação
print("Multiplicação de dois arrays:\n ", x / y)
print("Multiplicação com float/int:\n ", x / 2) #broadcast

In [7]:
## arrei contendo apenas N = Numer desejado
n = 5
n * np.one((10,10))

In [ ]:
#Multiplicação matricial
print("Multiplicação matricial de (np.dot):\n ", np.dot(x , y))
print("Multiplicação matricial (@):\n ", x @ 2)
print("Multiplicação matricial de (.dot):\n ", x.dot(2))

#porblema

In [ ]:
A = numpy.array([[1,2],[3,-2]])
c = numpy.array([[7],[-11]])
print("A: \n", A)
print("C: \n", C)

In [ ]:
#solução
x = np.dot(np.linalg.inv(A), c) #clacuca o inversso de A e multiplica por c
print("(a,b) :", x.revel())